export const LIST_ICON_COLORS = {
	LIGHT_BLUE: 'light-blue',
	BLUE: 'blue',
	PINK: 'pink',
	VIOLET: 'violet',
	GREEN: 'green',
	YELLOW: 'yellow',
	ORANGE: 'orange',
}

LIST_ICON_COLORS.LIST = [
	LIST_ICON_COLORS.LIGHT_BLUE,
	LIST_ICON_COLORS.BLUE,
	LIST_ICON_COLORS.PINK,
	LIST_ICON_COLORS.VIOLET,
	LIST_ICON_COLORS.GREEN,
	LIST_ICON_COLORS.YELLOW,
	LIST_ICON_COLORS.ORANGE,
]
